### ISSUE TITLE
Troubles exporting huge table

### ISSUE THREAD

**Issue by Corrosion667** [auto-mat/django-import-export-celery#76] opened 2022-06-23 12:13 UTC
Hello, I've faced troubles while exporting the table with 180.000+ rows.
Here is a traceback:
```
[2022-06-23 15:06:51,905: ERROR/ForkPoolWorker-17] Task import_export_celery.tasks.run_export_job[9ed87b13-927c-4acc-aad3-fa9d3a1243ea] raised unexpected: MemoryError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/import_export_celery/tasks.py", line 225, in run_export_job
    serialized = format.export_data(data)
  File "/usr/local/lib/python3.9/site-packages/import_export/formats/base_formats.py", line 88, in export_data
    return dataset.export(self.get_title(), **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tablib/core.py", line 427, in export
    return fmt.export_set(self, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tablib/formats/_csv.py", line 33, in export_set
    return stream.getvalue()
MemoryError   
[2022-06-23 15:06:54,726: ERROR/MainProcess] Pool callback raised exception: MemoryError('Process got: ')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1796, in safe_apply_callback
    fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 730, in on_success
    return self.on_failure(retval, return_ok=True)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/request.py", line 545, in on_failure
    raise MemoryError(f'Process got: {exc}')
MemoryError: Process got: 
```
It crashes at the very end of exporting:
![изображение](https://user-images.githubusercontent.com/85584435/175295548-8b76f033-95d5-4a4b-9085-67906ac93650.png)

I have no idea what to do. Here is what command 'top' showing at the end of the process while crashing. It seems my server has enough memory:
![изображение](https://user-images.githubusercontent.com/85584435/175295746-56ceb586-973a-465e-ab98-d91e8df8537f.png)
![изображение](https://user-images.githubusercontent.com/85584435/175305270-68150e10-ff63-4060-877e-ea75550cb664.png)

Concurrency is not specified. Celery takes 16 as default (as server has).

For example, model with 40.000 rows exported successfully and much faster.

Any ideas, please?

**Comment by Corrosion667** [comment] 2022-06-23 13:58
Did I clearly understand that writing in a file happens as a single operation. We do not use a generator or something like this to write by chunks?

```
export_job.file.save(filename, ContentFile(serialized))
```

**Comment by Corrosion667** [comment] 2022-06-24 08:32
Created swap file on my server. Export was successfully.
@timthelion Is there any way to write in file by chunks? Because as tablib maintainers said, their lib is not for working with big data.
I think i could try to implement this one day.

**Comment by timthelion** [comment] 2022-06-24 09:46
Unfortunately this is just,a,wrapper for django-import-export-celery which doesn't do streaming writes, indeed, it supports file formats such as xls which are not appendable.

**Comment by timthelion** [comment] 2022-06-24 09:47
I think that either we can create a special big data driver thatonly supports appendable formats suchas csv, or we can make it so that multiple files are saved. What is preferable for you?

**Comment by Corrosion667** [comment] 2022-06-24 10:00
Thank you for the answer!
One file is preferable for me. So that driver would be the best solution.

**Comment by timthelion** [comment] 2022-06-24 10:22
This is really a duplicate of https://github.com/auto-mat/django-import-export-celery/issues/37 so I'm closing this for now so that things stay tidy.

**Closed by timthelion** 2022-06-24 10:22 UTC
