### ISSUE TITLE
Unexpected RemovedInDjango51Warning due to the import of get_storage_class

### ISSUE THREAD

**Issue by JMSoler7** [auto-mat/django-import-export-celery#115] opened 2024-02-19 10:59 UTC
This method from the django.core.files.storage module is deprecated as of Django 5.1.

It's easy to reproduce; simply define a custom IMPORT_EXPORT_CELERY_STORAGE in the config settings and reload the application:

```bash
/app/.venv/lib/python3.11/site-packages/import_export_celery/fields.py:10: RemovedInDjango51Warning: django.core.files.storage.get_storage_class is deprecated in favor of using django.core.files.storage.storages.
    storage_class = get_storage_class(settings.IMPORT_EXPORT_CELERY_STORAGE)
```
Upon inspecting the Django documentation (https://docs.djangoproject.com/en/5.0/ref/files/storage/#django.core.files.storage.get_storage_class), there is an explanation to use storages (https://docs.djangoproject.com/en/5.0/ref/files/storage/#django.core.files.storage.storages) instead of the get_storage_class method.

**Comment by timthelion** [comment] 2024-02-19 11:24
Can this be fixed in a backwards compatible fashion?

**Comment by JMSoler7** [comment] 2024-02-19 11:34
@timthelion I'm going to create a pull request in a few minutes which fits with all versions :smiley:

**Comment by PetrDlouhy** [comment] 2024-05-21 14:44
@JMSoler7 The logic of the PR seems to me to be quite harmful. I have written a comment on the PR, but there are other problems:

- Switching to default storage when `InvalidStorageError` could lead to very unexpected behavior when there is some problem with the storage. I don't think it is equivalent with defaulting to `default` storage.
- I don't think the code is backward compatible with applications not using the new `STORAGES` settings since `settings.STORAGES.get("IMPORT_EXPORT_CELERY_STORAGE")["BACKEND"]` will throw error if `STORAGES` are not used.

**Closed** 2024-05-24 13:41 UTC
